version: 0.1.{build}

install:
    - nuget restore

build:
        project: Tracki.sln
        verbosity: detailed

environment:
        COVERALLS_REPO_TOKEN:  
                secure: wXJE8qYupJAXuxr49ybw6HJHVBDrgd4dtrnOF0xCWVI=

after_test: 
        - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunners.3.6.0\tools\nunit3-console.exe" -targetargs:"/noshadow /domain:single  Tracki.Tests\bin\debug\Tracki.Tests.dll" -output:coverage.xml

        - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
